autotest/urls.py
from django.contrib import admin
from django.urls import path
from apitest import views    #加入引用
from product import proviews
from bug import bugviews
from set import setviews
from apptest import appviews
from webtest import webviews

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('test/', views.test),    #加入关联路径函数
    path('login/', views.login),
    path('home/', views.home),    #加入
    path('logout/', views.logout),
    path('product_manage/', proviews.product_manage),
    path('apitest_manage/', views.apitest_manage),
    path('apistep_manage/', views.apistep_manage),
    path('apis_manage/', views.apis_manage),
    path('bug_manage/', bugviews.bug_manage),
    path('set_manage/', setviews.set_manage ),
    path('user/', setviews.set_user),
    path('appcase_manage/', appviews.appcase_manage),
    path('appcasestep_manage/', appviews.appcasestep_manage),
    path('webcase_manage/', webviews.webcase_manage),
    path('webcasestep_manage/', webviews.webcasestep_manage),
    path('test_report/', views.test_report),
    path('apptest_report/', appviews.apptest_report),
    path('left/', views.left),
    path('apisearch/', views.apisearch),
    path('setsearch/', setviews.setsearch),
    path('productsearch/', proviews.productsearch),
    path('apissearch/', views.apissearch),
    path('bugsearch/', bugviews.bugsearch),
    path('appsearch/', appviews.appsearch),
    path('appstepsearch/', appviews.appstepsearch),
    path('websearch/', webviews.websearch),
    path('webstepsearch/', webviews.webstepsearch),
    path('usersearch/', setviews.usersearch),
    path('welcome/',views.welcome),
]

apitest/models.py
from product.models import Product
from django.db import models

# Create your models here.

class Apitest(models.Model):
	#product = models.ForeignKey(product.Product)
	Product = models.ForeignKey('product.Product', on_delete = models.CASCADE, null = True)	
	#关联产品ID，其中product是应用名，Product是product应用的表名
	apitestname = models.CharField('流程接口名称', max_length = 64)	#流程接口测试场景
	apitestdesc = models.CharField('描述', max_length = 64, null = True)		#流程接口描述
	apitester = models.CharField('测试负责人',max_length = 16)	#执行人
	apitestresult = models.BooleanField('测试结果')	#流程接口测试结果
	create_time = models.DateTimeField('创建时间', auto_now = True)	#创建时间，自动获取当前时间

	
	class Meta:
		verbose_name = '流程场景接口'
		verbose_name_plural = '流程场景接口'
	def __str__(self):
		return self.apitestname

class Apistep(models.Model):
	#Apitest = models.ForeignKey('Apitest', on_delete = models.CASCADE,)	#关联接口ID
	Apitest = models.ForeignKey('Apitest', on_delete = models.CASCADE)
	apiname = models.CharField('接口名称', max_length = 100)		#接口标题
	apiurl = models.CharField('url地址', max_length = 200)		#地址
	apistep = models.CharField('测试步骤', max_length = 100, null = True)	#测试步骤
	apiparamvalue = models.CharField('请求参数和值', max_length = 800)		#参数和值
	REQUEST_METHOD = (('get', 'get'),('post', 'post'),('put', 'put'),('delete', 'delete'),('patch', 'patch'))
	apimethod = models.CharField(verbose_name = '请求方法', choices = REQUEST_METHOD, default = 'get', max_length = 200, null = True)	#请求方法
	apiresult = models.CharField('预期结果', max_length = 200)	#预期结果
	#apiresponse = models.CharField('响应数据', max_length = 5000, null = True)	#响应数据
	apistatus = models.CharField('是否通过', max_length = 16)		#测试结果
	create_time = models.DateTimeField('创建时间', auto_now = True)	#创建时间，自动获取当前时间


	def __str__(self):
		return self.apiname

class Apis(models.Model):
	Product = models.ForeignKey('product.Product', on_delete=models.CASCADE, null=True)	#关联产品ID
	apiname = models.CharField('接口名称', max_length=100)	#接口标题
	apiurl = models.CharField('url 地址', max_length=200)	#地址
	apiparamvalue = models.CharField('请求参数和值', max_length=800)	#请求参数和值
	REQUEST_METHOD = (('0', 'get'), ('1', 'post'), ('2', 'put'), ('3', 'delete'), ('4', 'patch'))
	apimethod = models.CharField(verbose_name='请求方法', choices=REQUEST_METHOD, default='0', max_length=200)	#请求方法
	apiresult = models.CharField('预期结果', max_length=200)	#预期结果
	apistatus = models.BooleanField('是否通过')		#测试结果
	create_time = models.DateTimeField('创建时间', auto_now=True)	#创建时间，自动获取当前时间

	class Meta:
		verbose_name='单一场景接口'
		verbose_name_plural='单一场景接口'

	def __str__(self):
		return self.apiname

apitest/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect      #加入引用
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from apitest.models import Apitest,Apistep,Apis
import pymysql
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
#import HTMLTestRunner

# Create your views here.

def test(request):
    return HttpResponse("hello test")    #返回HttpResponse响应函数

def welcome(request):
    return render(request, 'welcome.html')

def login(request):
    if request.POST:
        username = password = ''
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            request.session['user'] = username
            response = HttpResponseRedirect('/home/')
            return response
        else:
            return render(request, 'login.html', {'error', 'username or password error'})
    #else:
     #   context = {}
      #  return render(request, 'login.html', context)

    return render(request, 'login.html')

def home(request):
    return render(request, "home.html")

def logout(request):
    auth.logout(request)
    return render(request, 'login.html')

# 流程接口管理
@login_required
def apitest_manage(request):
    apitest_list = Apis.objects.all()    #获取所有接口测试用例
    apitest_count = Apitest.objects.all().count()   #统计产品数量
    username = request.session.get('user', '')  #读取浏览器登录session
    paginator = Paginator(apitest_list, 8)  #生成paginator对象， 设置每页显示8条记录
    page = request.GET.get('page', 1)   #获取当前的页码数，默认为第1页
    currentPage = int(page) #把获取的当前页码数转换成整数类型
    try:
        apitest_list = paginator.page(page) #获取当前页码数的记录列表
    except PageNotAnInteger:
        apitest_list = paginator.page(1)    #如果输入的页数不是整数，则显示第一页内容
    except EmptyPage:
        apitest_list = paginator.page(paginator.num_pages)  #如果输入的页数不在系统的页数中，则显示最后一页内容
    return render(request, "apitest_manage.html", {"user": username, "apitests": apitest_list, "apitestcounts": apitest_count}) #定义流程接口数据的变量并返回到前端

# 流程接口测试步骤
@login_required
def apistep_manage(request):
    apistep_list = Apis.objects.all()    #获取所有接口测试用例
    apistep_count = Apistep.objects.all().count()
    username = request.session.get('user', '')  #读取浏览器登录session
    paginator = Paginator(apistep_list, 8)  #生成paginator对象， 设置每页显示8条记录
    page = request.GET.get('page', 1)   #获取当前的页码数，默认为第1页
    currentPage = int(page) #把获取的当前页码数转换成整数类型
    try:
        apistep_list = paginator.page(page) #获取当前页码数的记录列表
    except PageNotAnInteger:
        apistep_list = paginator.page(1)    #如果输入的页数不是整数，则显示第一页内容
    except EmptyPage:
        apistep_list = paginator.page(paginator.num_pages)  #如果输入的页数不在系统的页数中，则显示最后一页内容
    return render(request, "apistep_manage.html", {"user": username, "apisteps": apistep_list, "apistepcounts": apistep_count})

# 单一接口测试
@login_required
def apis_manage(request):
    apis_list = Apis.objects.all()    #获取所有接口测试用例
    apis_count = Apis.objects.all().count() #统计产品数
    username = request.session.get('user', '')  #读取浏览器登录session
    paginator = Paginator(apis_list, 8)  #生成paginator对象， 设置每页显示8条记录
    page = request.GET.get('page', 1)   #获取当前的页码数，默认为第1页
    currentPage = int(page) #把获取的当前页码数转换成整数类型
    try:
        apis_list = paginator.page(page) #获取当前页码数的记录列表
    except PageNotAnInteger:
        apis_list = paginator.page(1)    #如果输入的页数不是整数，则显示第一页内容
    except EmptyPage:
        apis_list = paginator.page(paginator.num_pages)  #如果输入的页数不在系统的页数中，则显示最后一页内容
    return render(request, "apis_manage.html", {"user": username, "apiss": apis_list, "apiscounts": apis_count})    #把值赋给apiscounts变量

# 测试报告
@login_required
def test_report(request):
    username = request.session.get('user', '')
    apis_list = Apis.objects.all()
    apis_count = Apis.objects.all().count() #统计接口数
    db = pymysql.connect(user='root', db='autotest', passwd='123456', host='127.0.0.1')
    cursor = db.cursor()
    sql1 = 'SELECT count(id) FROM apitest_apis WHERE apitest_apis.apistatus=1'
    aa = cursor.execute(sql1)
    apis_pass_count = [row[0] for row in cursor.fetchmany(aa)][0]
    sql2 = 'SELECT count(id) FROM apitest_apis WHERE apitest_apis.apistatus=0'
    bb = cursor.execute(sql2)
    apis_fail_count = [row[0] for row in cursor.fetchmany(bb)][0]
    db.close()
    return render(request, "report.html", {"user": username, "apiss":apis_list, "apiscounts":apis_count, "apis_pass_counts": apis_pass_count, "apis_fail_counts": apis_fail_count}) #把值赋给apiscounts变量

def left(request):
    return render(request, "left.html")

#搜索功能
@login_required
def apisearch(request):
    username =request.session.get('user', '')   #读取浏览器登录session
    search_apitestname = request.GET.get("apitestname", "")
    apitest_list = Apitest.objects.filter(apitestname__icontains=search_apitestname)
    return render(request, 'apitest_manage.html', {"user": username, "apitests": apitest_list})
@login_required
def apissearch(request):
    username = request.session.get('user', '')
    search_apiname = request.GET.get("apiname", "")
    apis_list = Apis.objects.filter(apiname__icontains=search_apiname)
    return render(request, 'apis_manage.html', {"user": username, "apiss": apis_list})

apitest/templates/apis_manage.html
<!-----------------------------------------
# @Time    : 2019/1/13 15:57
# @Author  : Jhin•W
# @Email   : 261229090@qq.com
# @File    : apis_manage.py
# @Software: PyCharm
 ------------------------------------------>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>产品自动化测试管理平台</title>

<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
<meta name="robots" content="NONE,NOARCHIVE" />

</head>
<body role="document">
<!-- 搜索栏 -->
<div class="page-header" style="padding-top: 70px;">
    <form class="navbar-form" method="get" action="/apissearch/">
        {% csrf_token %}
        <input type="search" name="apiname" placeholder="名称" required>
        <button type="submit">搜索</button>
<!-- 增加api单一接口测试用例-->
<div style="float:right;width:65%">

<select name="Apis" id="id_Apis">
<option value="" selected>----api单一接口测试用例----</option>
</select>
<a class="related-widget-wrapper-link change-related" id="change_id_Apis" data-href-template="/admin/apitest/apis/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
<img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
</a>
<a class="related-widget-wrapper-link add-related" id="add_id_Apis" href="/admin/apitest/apis/add/?_to_field=id&amp;_popup=1" title="增加另一个 测试用例">
<img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
</a>
</div>
    </form>
</div>
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
<a class="navbar-brand" href="#">&nbsp;</a>
<ul class="nav justify-content-center">
    <li><a style="color: white" href="/apitest_manage/">流程接口测试用例</a></li>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <li class="active"><a style="color: white" href="/apistep_manage/">流程接口测试步骤</a></li>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <li class="active"><a style="color: white" href="/apis_manage/">单一接口测试用例</a></li>
</ul>
<ul class="nav justify-content-end">
<li class="nav-link"><a style='color:white' href="#">{{user}}</a></li>
<li class="nav-link"><a style='color:white' href="/logout/">退出</a></li>
</ul>
</div>
</nav>
<!-- 单一接口测试用例-->
<div class="row" style="padding-top: 70px;">
<div class="col-md-11">
<table class="table table-striped">
<thead>
<tr>
<th>ID</th><th>产品</th><th>单一接口测试用例名称</th><th>URL地址</th><th>参数值</th><th>方法</th><th>预期结果</th><th>测试结果</th><th>测试人</th><th>时间</th>
</tr>
</thead>
<tbody>
{% for apis in apiss %}
<tr>
<td>{{apis.id}}</td>
<td>{{ apis.Product.productname }}</td>
<td>{{ apis.apiname }}</td>
<td>{{ apis.apiurl }}</td>
<td>{{ apis.apiparamvalue }}</td>
<td>{{ apis.apimethod }}</td>
<td>{{ apis.apiresult }}</td>
<td>{% if apis.apistatus == 1 %}
<a style='color:green'>{{ apis.apistatus }}</a>
{% else %}
<a style='color:red'>{{ apis.apistatus }}</a>
{% endif %}
</td>
<td>{{ apis.apitester }}</td>
<td>{{ apis.create_time }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>


<td><a style="color: light blue" class="related-widget-wrapper-link add-related" id="add_id_Apis" href="../admin/apitest/apis/{{ apis.id }}/change/?_to_field=id&_popup=1">
    <img src="/static/admin/img/icon-changelink.svg" alt="编辑"/>编辑</a></td>
<td><a style="color: light blue" class="related-widget-wrapper-link add-related" id="add_id_Apis" href="../admin/apitest/apis/{{ apis.id }}/change/?_to_field=id&_popup=1">
    <img src="/static/admin/img/icon-changelink.svg" alt="删除"/>删除</a></td>

<div class="container">
<span style="position: absolute; right: 100px; bottom: 100px;">
<div style="position: absolute; right: 100px; width: 100px;">
    <tr><th>总数</th><td>{{ apiscounts }}</td></tr>    {# 前端读取定义的变量 #}
</div>
    <ul class="pagination" id="pager">
        {# 上一页链接开始 #}
        {% if apis.has_previous %}
        {# 如果有上一页，则正常显示上一页链接 #}
        <li class="previous"><a href="/apis_manage/?page={{ apiss.previous_page_number }}">上一页</a></li>
        {# 上一页标签 #}
        {% else %}
        <li class="previous disabled"><a href="#">上一页</a></li>
        {# 如果当前不存在上一页，则上一页的链接不可单击 #}
        {% endif %}
    {# 上一页链接结束 #}
    {% for num in apis.paginator.page_range %}
    {% if num == currentPage %}
    <li class="item active"><a href="/apis_manage/?page={{ num }}">{{ num }}</a></li>
    {# 显示当前页数链接 #}
    {% else %}
    <li class="item"><a href="/apis_manage/?page={{ num }}">{{ num }}</a></li>
    {% endif %}
    {% endfor %}
    {# 下一页链接开始 #}
    {% if apis.has_next %}{# 如果有下一页，则正常显示下一页链接 #}
    <li class="next"><a href="/apis_manage/?page={{ apiss.next_page_number }}">下一页</a></li>
    {% else %}
    <li class="next disabled"><a href="#">下一页</a></li>
    {% endif %}
    {# 下一页链接结束 #}
    </ul>
</span>
</div>

</body>
</html>

apitest/templates/apitest_manage.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<title>自动化测试平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
<meta name="robots" content="NONE,NOARCHIVE" />

<!-- 增加api流程测试流程用例 -->
    <div style="float: right;width: 73%">
        <select name="Apitest" id="id_Apitest">
            <option value="" selected>----api流程测试用例----</option>
        </select>
        <a class="related-widget-wrapper-link change-related" id="change_id_Apitest" data-href-template="/admin/apitest/apitest/__fk__/change/?_to_field=id&amp; _popup=1" title="更改选中的测试用例">
            <img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
        </a>
        <a class="related-widget-wrapper-link change-related" id="add_id_Apitest" href="/admin/apitest/apitest/add/?_to_field=id&amp; _popup=1" title="增加另一个测试用例">
            <img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
        </a>
    </div>
</head>
<body role="document">
<!-- 搜索栏 -->
<div class="page-header" style="padding-top: 70px;">
    <form class="navbar-form" method="get" action="/apisearch/">
        {% csrf_token %}
        <input type="search" name="apitestname" placeholder="名称" required>
        <button type="submit">搜索</button>
    </form>
</div>
<!-- 导航栏-->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
<div class="container">
    <a class="navbar-brand" href="#">&nbsp;</a>
    <ul class="nav justify-content-center">
        <li class="active"><a style="color: white" href="/apitest_manage">流程接口测试</a></li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <li class="active"><a style="color: white" href="/apistep_manage">流程接口测试步骤</a></li>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <li class="active"><a style="color: white" href="/apis_manage">单一接口测试用例</a> </li>
    </ul>
    <ul class="nav justify-content-end">
        <li class="nav-link"><a style="color: white" href="#">{{ user }}</a></li>
        <li class="nav-link"><a style="color: white" href="/logout/">退出</a></li>
    </ul>
</div>
</nav>
<!-- 流程接口列表 -->
<div class="row" style="padding-top: 70px;">
    <div class="col-md-11">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th><th>业务接口流程名称</th><th>执行人</th><th>结果</th><th>时间</th>
            </tr>
            </thead>
            <tbody>
            {% for apitest in apitests %}
            <tr>
                <td>{{ apitest.id }}</td>
                <td>{{ apitest.apitestname }}</td>
                <td>{{ apitest.apitester }}</td>
                <td>{{ apitest.apitestresult }}</td>
                <td>{{ apitest.create_time }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<td><a style="color: light blue" class="related-widget-wrapper-link add-related" id="add_id_Apitest" href="../admin/apitest/apitest/{{ apitest.id }}/change/?_to_field=id&_popup=1">
    <img src="/static/admin/img/icon-changelink.svg" alt="编辑"/>编辑</a></td>
<td><a style="color: light blue" class="related-widget-wrapper-link add-related" id="add_id_Apitest" href="../admin/apitest/apitest/{{ apitest.id }}/change/?_to_field=id&_popup=1">
    <img src="/static/admin/img/icon-changelink.svg" alt="删除"/>删除</a></td>

<div class="container">
<span style="position: absolute; right: 100px; bottom: 30px;">  {# 把翻页功能固定在右下角 #}
<div style="position: absolute; right: 100px; width: 100px;">
    <tr><th>总数</th><td>{{ apitestcounts }}</td></tr>    {# 前端读取定义的变量 #}
</div>
    <ul class="pagination" id="pager">
        {# 上一页链接开始 #}
        {% if apitests.has_previous %}
        {# 如果有上一页，则正常显示上一页链接 #}
        <li class="previous"><a href="/apitest_manage/?page={{ apitests.previous_page_number }}">上一页</a></li>
        {# 上一页标签 #}
        {% else %}
        <li class="previous disabled"><a href="#">上一页</a></li>
        {# 如果当前不存在上一页，则上一页的链接不可单击 #}
        {% endif %}
    {# 上一页链接结束 #}
    {% for num in apitests.paginator.page_range %}
    {% if num == currentPage %}
    <li class="item active"><a href="/apitest_manage/?page={{ num }}">{{ num }}</a></li>
    {# 显示当前页数链接 #}
    {% else %}
    <li class="item"><a href="/apitest_manage/?page={{ num }}">{{ num }}</a></li>
    {% endif %}
    {% endfor %}
    {# 下一页链接开始 #}
    {% if apitests.has_next %}{# 如果有下一页，则正常显示下一页链接 #}
    <li class="next"><a href="/apitest_manage/?page={{ apitests.next_page_number }}">下一页</a></li>
    {% else %}
    <li class="next disabled"><a href="#">下一页</a></li>
    {% endif %}
    {# 下一页链接结束 #}
    </ul>
</span>
</div>

</body>
</html>

apitest/templates/home.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Frameset//EN" "http://www.w3.org/TR/html4/frameset.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>自动化测试平台</title>
</head>
  <frameset id="frame1" rows="*" cols="285,*" framespacing="0" frameborder="yes" border="0">
    <frame src="../left" name="leftFrame" scrolling="auto" noresize>
    <frame src="../welcome" name="mainFrame" scrolling="NO"  noresize>
  </frameset>
<noframes>
<body>
<ul class="nav navbar-nav navbar-right">
<li>欢迎您，<a href="../admin/">{{user}}</a></li>
<li><a href="/logout/"  target="_top">退出</a></li>
</ul>
</body>
</noframes>
</html>

apitest/templates/login.html
<!DOCTYPE html>
<html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>AutotestPlat</title>
<style> body{text-align: center} </style>
</head>
<body>
<div>
<font size="5">
    <span style="font-weight:bold;"> <hl>自动化平台测试开发</hl> </span>
</font>
<form method="post" action="/login/">
{% csrf_token %}
<br><a>&nbsp;&nbsp;用户名：</a> <input name="username" type="text" placeholder="username">
<br><br> <a>&nbsp;&nbsp;密&nbsp;码：</a> <input name="password" type="password" placeholder="password">
<br>{{error}}<br>
&nbsp; <button style="width: 220px;height: 28px;" id="submit" type="submit">登 录
</button>
</form>
</div>
</body>
</html>

apitest/templates/product_manage.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <title>产品自动化测试平台</title>
</head>
<body role="document">
<!-- 导航栏 -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">&nbsp;</a>
        <ul class="nav justify-content-center">
        </ul>
        <ul class="nav justify-content-end">
            <li class="nav-link"><a style="color: white" href="#">{{ user }}</a></li>
            <li class="nav-link"><a style="color: white" href="/logout/">退出</a></li>
        </ul>
    </div>
</nav>

<!--产品列表-->
<div class="row" style="padding-top: 20px;">
<div class="col-md-11">
    <table class="table table-striped">
        <thead>
        <tr><td>&nbsp;</td></tr>
        <tr>
            <th>ID</th><th>产品名称</th><th>产品描述</th><th>产品负责人</th><th>创建时间</th>
        </tr>
        </thead>
        <tbody>
        {% for product in products %}
            <tr>
            <td>{{ product.id }}</td>
            <td>{{ product.productname }}</td>
            <td>{{ product.productdesc }}</td>
            <td>{{ product.producter }}</td>
            <td>{{ product.create_time }}</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
</div>

</body>
</html>