autotest/urls.py
from django.contrib import admin
from django.urls import path
from apitest import views    #加入引用
from product import proviews
from bug import bugviews
from set import setviews
from apptest import appviews
from webtest import webviews

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('test/', views.test),    #加入关联路径函数
    path('login/', views.login),
    path('home/', views.home),    #加入
    path('logout/', views.logout),
    path('product_manage/', proviews.product_manage),
    path('apitest_manage/', views.apitest_manage),
    path('apistep_manage/', views.apistep_manage),
    path('apis_manage/', views.apis_manage),
    path('bug_manage/', bugviews.bug_manage),
    path('set_manage/', setviews.set_manage ),
    path('user/', setviews.set_user),
    path('appcase_manage/', appviews.appcase_manage),
    path('appcasestep_manage/', appviews.appcasestep_manage),
    path('webcase_manage/', webviews.webcase_manage),
    path('webcasestep_manage/', webviews.webcasestep_manage),
    path('test_report/', views.test_report),
    path('apptest_report/', appviews.apptest_report),
    path('left/', views.left),
    path('apisearch/', views.apisearch),
    path('setsearch/', setviews.setsearch),
    path('productsearch/', proviews.productsearch),
    path('apissearch/', views.apissearch),
    path('bugsearch/', bugviews.bugsearch),
    path('appsearch/', appviews.appsearch),
    path('appstepsearch/', appviews.appstepsearch),
    path('websearch/', webviews.websearch),
    path('webstepsearch/', webviews.webstepsearch),
    path('usersearch/', setviews.usersearch),
    path('welcome/',views.welcome),
]

webtest/models.py
from django.db import models
from product.models import Product
# Create your models here.

class Webcase(models.Model):
    Product = models.ForeignKey('product.Product', on_delete=models.CASCADE, null=True)
    webcasename = models.CharField('用例名称', max_length=200)
    webtestresult = models.BooleanField('测试结果')
    webtester = models.CharField('测试负责人', max_length=16)
    create_time = models.DateTimeField('创建时间', auto_now=True)

    class Meta:
        verbose_name = 'web 测试用例'
        verbose_name_plural = 'web 测试用例'

    def __str__(self):
        return self.webcasename

class Webcasestep(models.Model):
    Webcase = models.ForeignKey(Webcase,on_delete=models.CASCADE)
    webcasename = models.CharField('测试用例标题', max_length=200)
    webteststep = models.CharField('测试步骤', max_length=200)
    webtestobjname = models.CharField('测试对象名称描述', max_length=200)
    webfindmethod = models.CharField('定位方式', max_length=200)
    webevelement = models.CharField('控件元素', max_length=200)
    weboptmethod = models.CharField('操作方法', max_length=200)
    webtestdata = models.CharField('测试数据', max_length=200, null=True)
    webassertdata = models.CharField('验证数据', max_length=200)
    webtestresult = models.BooleanField('测试结果')
    create_time = models.DateTimeField('创建时间', auto_now=True)

    def __str__(self):
        return self.webcasename

webtest/templates/webcase_manage.html
<!-----------------------------------------
# @Time    : 2019/1/14 20:12
# @Author  : Jhin•W
# @Email   : 261229090@qq.com
# @File    : webcase_manage.py
# @Software: PyCharm
 ------------------------------------------>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <title>产品自动化测试管理平台</title>
<link href="../static/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />



<script type="text/javascript" src="/admin/jsi18n/"></script>

<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>

<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>

<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>

<script type="text/javascript" src="/static/admin/js/urlify.js"></script>

<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>

<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>



<meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">

<link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />



<meta name="robots" content="NONE,NOARCHIVE" />
</head>
<body role="document">
<!-- 搜索栏 -->
<div class="page-header" style="padding-top: 70px;">
    <form class="navbar-form" method="get" action="/websearch/">
        {% csrf_token %}
        <input type="search" name="webcasename" placeholder="名称" required>
        <button type="submit">搜索</button>
<!-- 增加web测试用例-->
<div style="float:right;width:65%">

<select name="Webcase" id="id_Webcase">
<option value="" selected>----web测试用例----</option>
</select>
<a class="related-widget-wrapper-link change-related" id="change_id_Webcase" data-href-template="/admin/webtest/webcase/__fk__/change/?_to_field=id&amp;_popup=1" title="更改选中的测试用例">
<img src="/static/admin/img/icon-changelink.svg" alt="修改"/>
</a>
<a class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="/admin/webtest/webcase/add/?_to_field=id&amp;_popup=1" title="增加另一个 测试用例">
<img src="/static/admin/img/icon-addlink.svg" alt="增加"/>增加
</a>
</div>
    </form>
</div>
<!-- 导航栏 -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">&nbsp;</a>
        <ul class="nav justify-content-center">
            <li><a style="color: white" href="/webcase_manage/">web 测试用例</a></li>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <li><a style="color: white" href="/webcasestep_manage/">web 测试用例步骤</a></li>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </ul>
        <ul class="nav justify-content-end">
            <li class="nav-link"><a style="color: white" href="#">{{ user }}</a></li>
            <li class="nav-link"><a style="color: white" href="/logout/">退出</a></li>
        </ul>
    </div>
</nav>
<!-- web 测试用例列表 -->
<div class="row" style="padding-top: 20px;">
    <div class="col-md-11">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th><th>产品</th><th>测试用例名称</th><th>测试结果</th><th>测试负责人</th><th>时间</th><th>测试用例步骤</th>
            </tr>
            </thead>
            <tbody>
            {% for webcase in webcases %}
            <tr>
            <td>{{ webcase.id }}</td>
            <td>{{ webcase.Product.productname }}</td>
            <td>{{ webcase.webcasename }}</td>
            <td>{{ webcase.webtestresult }}</td>
            <td>{{ webcase.webtester }}</td>
            <td>{{ webcase.create_time }}</td>
            <td><a href="#">{{ webcase.webcasestep }}</a></td>
            <td>{{ webcase.webcasestep }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<td><a style="color: light blue" class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="../admin/webtest/webcase/{{ webcase.id }}/change/?_to_field=id&_popup=1">
    <img src="/static/admin/img/icon-changelink.svg" alt="编辑"/>编辑</a></td>
<td><a style="color: light blue" class="related-widget-wrapper-link add-related" id="add_id_Webcase" href="../admin/webtest/webcase/{{ webcase.id }}/change/?_to_field=id&_popup=1">
    <img src="/static/admin/img/icon-changelink.svg" alt="删除"/>删除</a></td>

<div class="container">
<span style="position: absolute; right: 100px; bottom: 30px;">
<div style="position: absolute; right: 100px; width: 100px;">
    <tr><th>总数</th><td>{{ webcasecounts }}</td></tr>    {# 前端读取定义的变量 #}
</div>
    <ul class="pagination" id="pager">
        {# 上一页链接开始 #}
        {% if webcases.has_previous %}
        {# 如果有上一页，则正常显示上一页链接 #}
        <li class="previous"><a href="/webcase_manage/?page={{ webcases.previous_page_number }}">上一页</a></li>
        {# 上一页标签 #}
        {% else %}
        <li class="previous disabled"><a href="#">上一页</a></li>
        {# 如果当前不存在上一页，则上一页的链接不可单击 #}
        {% endif %}
    {# 上一页链接结束 #}
    {% for num in webcases.paginator.page_range %}
    {% if num == currentPage %}
    <li class="item active"><a href="/webcase_manage/?page={{ num }}">{{ num }}</a></li>
    {# 显示当前页数链接 #}
    {% else %}
    <li class="item"><a href="/webcase_manage/?page={{ num }}">{{ num }}</a></li>
    {% endif %}
    {% endfor %}
    {# 下一页链接开始 #}
    {% if webcases.has_next %}{# 如果有下一页，则正常显示下一页链接 #}
    <li class="next"><a href="/webcase_manage/?page={{ webcases.next_page_number }}">下一页</a></li>
    {% else %}
    <li class="next disabled"><a href="#">下一页</a></li>
    {% endif %}
    {# 下一页链接结束 #}
    </ul>
</span>
</div>
</body>
</html>

webtest/templates/webcasestep_manage.html
<!-----------------------------------------
# @Time    : 2019/1/14 20:24
# @Author  : Jhin•W
# @Email   : 261229090@qq.com
# @File    : webcasestep_manage.py
# @Software: PyCharm
 ------------------------------------------>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <meta charset="UTF-8">
    <title>产品自动化测试平台</title>
</head>
<body role="document">
<!-- 搜索栏 -->
<div class="page-header" style="padding-top: 70px;">
    <form class="navbar-form" method="get" action="/webstepsearch/">
        {% csrf_token %}
        <input type="search" name="webcasename" placeholder="名称" required>
        <button type="submit">搜索</button>
    </form>
</div>
<!-- 导航栏 -->
<nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">&nbsp;</a>
        <ul class="nav justify-content-center">
            <li><a style="color: white" href="/webcase_manage/">web 测试用例</a></li>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <li><a style="color: white" href="/webcasestep_manage/">web 测试用例步骤</a></li>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </ul>
        <ul class="nav justify-content-end">
            <li class="nav-link"><a style="color: white" href="#">{{ user }}</a></li>
            <li class="nav-link"><a style="color: white" href="/logout/">退出</a></li>
        </ul>
    </div>
</nav>
<!-- 用例测试步骤列表 -->
<div class="row" style="padding-top: 70px;">
    <div class="col-md-11">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>所属产品</th><th>所属用例</th><th>步骤</th><th>定位方式</th><th>控件元素</th><th>操作方法</th><th>测试数据</th><th>验证数据</th><th>测试结果</th><th>时间</th>
            </tr>
            </thead>
            <tbody>
            {% for webcasestep in webcasesteps %}
            <tr>
            <td>{{ webcasestep.Webcase.Product.productname }}</td>
            <td>case{{ webcasestep.Webcase.id }}:{{ webcasestep.Webcase.webcasename }}</td>
            <td>{{ webcasestep.webteststep }}:{{ webcasestep.webtestobjname }}</td>
            <td>{{ webcasestep.webfindmethod }}</td>
            <td>{{ webcasestep.webevelement }}</td>
            <td>{{ webcasestep.weboptmethod }}</td>
            <td>{{ webcasestep.webtestdata }}</td>
            <td>{{ webcasestep.webassertdata }}</td>
            <td>{% if webcasestep.webtestresult == 1 %}
            <a style="color: green">{{ webcasestep.webtestresult }}</a>
            {% else %}
            <a style="color: red">{{ webcasestep.webtestresult }}</a>
            {% endif %}
            </td>
            <td>{{ webcasestep.create_time }}</td>
            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>
<div class="container">
<span style="position: absolute; right: 100px; bottom: 30px;">
<div style="position: absolute; right: 100px; width: 100px;">
    <tr><th>总数</th><td>{{ webcasestepcounts }}</td></tr>    {# 前端读取定义的变量 #}
</div>
    <ul class="pagination" id="pager">
        {# 上一页链接开始 #}
        {% if webcasesteps.has_previous %}
        {# 如果有上一页，则正常显示上一页链接 #}
        <li class="previous"><a href="/webcasestep_manage/?page={{ webcasesteps.previous_page_number }}">上一页</a></li>
        {# 上一页标签 #}
        {% else %}
        <li class="previous disabled"><a href="#">上一页</a></li>
        {# 如果当前不存在上一页，则上一页的链接不可单击 #}
        {% endif %}
    {# 上一页链接结束 #}
    {% for num in webcasesteps.paginator.page_range %}
    {% if num == currentPage %}
    <li class="item active"><a href="/webcasestep_manage/?page={{ num }}">{{ num }}</a></li>
    {# 显示当前页数链接 #}
    {% else %}
    <li class="item"><a href="/webcasestep_manage/?page={{ num }}">{{ num }}</a></li>
    {% endif %}
    {% endfor %}
    {# 下一页链接开始 #}
    {% if webcasesteps.has_next %}{# 如果有下一页，则正常显示下一页链接 #}
    <li class="next"><a href="/webcasestep_manage/?page={{ webcasesteps.next_page_number }}">下一页</a></li>
    {% else %}
    <li class="next disabled"><a href="#">下一页</a></li>
    {% endif %}
    {# 下一页链接结束 #}
    </ul>
</span>
</div>
</body>
</html>